# Generated by Django 2.2.7 on 2019-11-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
