# Generated by Django 3.0 on 2019-12-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Post Catagories',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='catagories',
            field=models.ManyToManyField(to='blog.PostCatagory'),
        ),
    ]
