# Generated by Django 3.0 on 2019-12-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191213_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostCatagory',
            new_name='PostCategory',
        ),
        migrations.RenameField(
            model_name='postcategory',
            old_name='catagory_name',
            new_name='category_name',
        ),
    ]
