# Generated by Django 3.0 on 2019-12-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191213_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcategory',
            options={'verbose_name_plural': 'Post Categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catagories',
            new_name='categories',
        ),
    ]
