# Generated by Django 3.0 on 2020-01-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191213_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(blank=True, default='slug'),
        ),
    ]
